version: "3"

services:
  db_post:
    container_name: postgresdbposts
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - posts_data:/var/lib/postgresql/data

  api_post:
    container_name: jibjabpost
    depends_on: [db_post]
    build:
      context: ../jibjab_posts
      dockerfile: Dockerfile.multi
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: postgres
      DB_HOST: postgresdbposts
      DB_PORT: 5432
      AUTH_PORT: 8080
      AUTH_HOST: jibjabuser

  db_user:
    container_name: postgresdbusers
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - users_data:/var/lib/postgresql/data

  api_user:
    container_name: jibjabuser
    depends_on: [db_user]
    build:
      context: ../jibjab_users
      dockerfile: Dockerfile.multi
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: postgres
      DB_HOST: postgresdbusers
      DB_PORT: 5432
      JJ_SECRET: secret_key
      JJ_EXPIRATION: 1000000000

  db_message:
    container_name: postgresdbmessages
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - messages_data:/var/lib/postgresql/data

  api_message:
    container_name: jibjabmessage
    depends_on: [db_message]
    build:
      context: ../jibjab_message
      dockerfile: Dockerfile.multi
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: postgres
      DB_HOST: postgresdbmessages
      DB_PORT: 5432
      AUTH_PORT: 8080
      AUTH_HOST: jibjabuser
      CLIENT_URL: "http://jibjabclient:80"

  client:
    container_name: jibjabclient
    build:
      context: ../jib-jab-client
      dockerfile: Dockerfile

  revproxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 3001:80

volumes:
  posts_data:
  users_data:
  messages_data:
